### ISSUE TITLE
InfluxDB v2.x support

### ISSUE THREAD

**Issue by R-Studio** [jbrt/svc2influxdb#2]
Hi @jbrt thanks for your work!
I forked your project and rewrite it for InfluxDB v2.x. -> [svc2influxdb2](https://github.com/R-Studio/svc2influxdb2)

*This is only an information for you. You can close this issue.*

**Comment by jbrt** [comment]
Hi @R-Studio 

Sorry for this very very late answer to your message.
You're welcome

Regards
